"""empty message

Revision ID: d66e1cd328b4
Revises: a5cffa318ac2
Create Date: 2025-06-13 23:34:38.366661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66e1cd328b4'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=150), nullable=False),
    sa.Column('img', sa.String(length=50), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caption')
    )
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=150), nullable=False),
    sa.Column('post_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_ID'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('Like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_ID'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_ID'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_ID', sa.Integer(), nullable=False),
    sa.Column('post_ID', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['post_ID'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['story_ID'], ['Story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('Share')
    op.drop_table('Story')
    op.drop_table('Like')
    op.drop_table('Comment')
    op.drop_table('Post')
    op.drop_table('User')
    # ### end Alembic commands ###
